package com.lj4s.bean;

import org.joda.time.DateTime;

/**
 * Created with IntelliJ IDEA.
 * User: liu
 * Date: 13-9-5
 * Time: 上午11:22
 * To change this template use File | Settings | File Templates.
 */
public class Deal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.id
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.num_iid
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.title
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.taobao_title
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private String taobaoTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.begin_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private DateTime beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.expire_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private DateTime expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private String dealUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.price
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.list_price
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private Float listPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.image_url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_key
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private String dealKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.create_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.update_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    private DateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.id
     *
     * @return the value of deal.id
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.id
     *
     * @param id the value for deal.id
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.num_iid
     *
     * @return the value of deal.num_iid
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.num_iid
     *
     * @param numIid the value for deal.num_iid
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.title
     *
     * @return the value of deal.title
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.title
     *
     * @param title the value for deal.title
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.taobao_title
     *
     * @return the value of deal.taobao_title
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public String getTaobaoTitle() {
        return taobaoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.taobao_title
     *
     * @param taobaoTitle the value for deal.taobao_title
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setTaobaoTitle(String taobaoTitle) {
        this.taobaoTitle = taobaoTitle == null ? null : taobaoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.begin_time
     *
     * @return the value of deal.begin_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public DateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.begin_time
     *
     * @param beginTime the value for deal.begin_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setBeginTime(DateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.expire_time
     *
     * @return the value of deal.expire_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public DateTime getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.expire_time
     *
     * @param expireTime the value for deal.expire_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setExpireTime(DateTime expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_url
     *
     * @return the value of deal.deal_url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public String getDealUrl() {
        return dealUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_url
     *
     * @param dealUrl the value for deal.deal_url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setDealUrl(String dealUrl) {
        this.dealUrl = dealUrl == null ? null : dealUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.url
     *
     * @return the value of deal.url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.url
     *
     * @param url the value for deal.url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.price
     *
     * @return the value of deal.price
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.price
     *
     * @param price the value for deal.price
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.list_price
     *
     * @return the value of deal.list_price
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public Float getListPrice() {
        return listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.list_price
     *
     * @param listPrice the value for deal.list_price
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setListPrice(Float listPrice) {
        this.listPrice = listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.image_url
     *
     * @return the value of deal.image_url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.image_url
     *
     * @param imageUrl the value for deal.image_url
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_key
     *
     * @return the value of deal.deal_key
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public String getDealKey() {
        return dealKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_key
     *
     * @param dealKey the value for deal.deal_key
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setDealKey(String dealKey) {
        this.dealKey = dealKey == null ? null : dealKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.create_time
     *
     * @return the value of deal.create_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.create_time
     *
     * @param createTime the value for deal.create_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.update_time
     *
     * @return the value of deal.update_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public DateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.update_time
     *
     * @param updateTime the value for deal.update_time
     *
     * @mbggenerated Tue Aug 20 17:11:15 CST 2013
     */
    public void setUpdateTime(DateTime updateTime) {
        this.updateTime = updateTime;
    }
}
